# Introduction to Tensors with TensorFlow

## Overview

A **Tensor** is a multi-dimensional array used to store and manipulate data in machine learning and deep learning frameworks such as TensorFlow. Tensors are the fundamental data structures in TensorFlow and represent the flow of data through a computational graph.

Tensors generalize scalars, vectors, and matrices to higher dimensions, allowing TensorFlow to efficiently process complex data such as images, videos, and large datasets.

---

## Types of Tensors

Tensors can have different dimensions, also known as **ranks**. The rank of a tensor indicates the number of dimensions it contains.

### 1. Scalar (0D Tensor)

A scalar is a single numerical value with no dimensions.

**Example:**

```python
5
```

---

### 2. Vector (1D Tensor)

A vector is a one-dimensional array containing multiple values.

**Example:**

```python
[1, 2, 3, 4]
```

---

### 3. Matrix (2D Tensor)

A matrix is a two-dimensional array organized into rows and columns.

**Example:**

```python
[[1, 2],
 [3, 4]]
```

---

### 4. 3D Tensor

A 3D tensor consists of multiple matrices stacked together.

**Example:**

```python
[
 [[1, 2], [3, 4]],
 [[5, 6], [7, 8]]
]
```

---

### 5. Higher-Dimensional Tensors

Tensors with more than three dimensions are used to represent complex data structures such as images, videos, and batches of training data.

For example, a batch of color images may be represented as a 4D tensor with the following shape:

```python
[batch_size, height, width, channels]
```

**Example:**

```python
[32, 224, 224, 3]
```

Where:

* **32** = Number of images in a batch
* **224** = Height of each image
* **224** = Width of each image
* **3** = RGB color channels

---

## Why Are Tensors Important?

* Tensors are the core data structures used in TensorFlow.
* They enable efficient computations on CPUs, GPUs, and TPUs.
* They are used to represent input data, model parameters, and outputs.
* Tensors support automatic differentiation, which is essential for training neural networks.
* They provide a flexible way to handle data of varying dimensions.

---

## Conclusion

Tensors are the foundation of TensorFlow and modern deep learning. They allow data to be represented in multiple dimensions, making it possible to work with everything from simple numerical values to complex datasets such as images, videos, and large-scale machine learning applications.



# Representation of Tensors

The TensorFlow framework is designed for high-performance numerical computation and operates primarily using tensors. When using TensorFlow, you define models, train them, and perform computations using tensors. Tensors are the fundamental building blocks that enable TensorFlow to efficiently process and manipulate data.

A tensor in TensorFlow is represented as an object with several important properties:

## Components of a Tensor

### 1. Shape

The **shape** of a tensor describes its dimensions.

**Example:**

```python
[2, 3]
```

This represents a matrix with **2 rows** and **3 columns**.

---

### 2. Rank

The **rank** of a tensor refers to the number of dimensions it has.

Examples:

- Scalar → Rank 0
- Vector → Rank 1
- Matrix → Rank 2
- 3D Tensor → Rank 3

**Example:**

```python
[1, 2, 3]
```

This is a vector with **rank 1**.

---

### 3. Data Type

The **data type (dtype)** specifies the type of values stored in a tensor.

Common TensorFlow data types include:

- `float32`
- `float64`
- `int32`
- `int64`
- `bool`
- `string`

**Example:**

```python
tf.constant([1, 2, 3], dtype=tf.int32)
```

---

### 4. Device

The **device** indicates where the tensor is stored and processed.

Common devices include:

- CPU
- GPU
- TPU

TensorFlow automatically assigns tensors to available devices for efficient computation.

---

## Tensors in TensorFlow

TensorFlow provides a wide range of operations that can be applied to tensors, including:

- Mathematical operations
- Arithmetic computations
- Matrix operations
- Tensor transformations
- Reshaping operations
- Reduction operations
- Machine learning computations

These operations enable TensorFlow to efficiently build and train deep learning models.

## Conclusion

Tensors are the core data structures in TensorFlow. Each tensor is defined by its shape, rank, data type, and device placement. Understanding tensor representation is essential for working effectively with TensorFlow and building machine learning applications.

# Basic Tensor Operations in TensorFlow

TensorFlow provides a large set of tensor operations that enable efficient data manipulation and numerical computation. These operations form the foundation for building machine learning and deep learning models.

Below are some of the most commonly used tensor operations in TensorFlow.

## 1. Creating Tensors

You can create tensors using TensorFlow's built-in functions such as `tf.constant()`, `tf.Variable()`, `tf.zeros()`, and `tf.ones()`.

### Creating a Constant Tensor

```python
import tensorflow as tf

tensor = tf.constant([1, 2, 3, 4])
print(tensor)
```

### Creating a Variable Tensor

```python
import tensorflow as tf

variable = tf.Variable([10, 20, 30])
print(variable)
```

### Creating a Tensor of Zeros

```python
import tensorflow as tf

zeros_tensor = tf.zeros((2, 3))
print(zeros_tensor)
```

### Creating a Tensor of Ones

```python
import tensorflow as tf

ones_tensor = tf.ones((2, 3))
print(ones_tensor)
```

### Creating a Random Tensor

```python
import tensorflow as tf

random_tensor = tf.random.normal((2, 3))
print(random_tensor)
```

## Output Examples

### Constant Tensor

```python
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
```

### Zero Tensor

```python
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]],
shape=(2, 3),
dtype=float32)
```

## Key Points

- `tf.constant()` creates immutable tensors.
- `tf.Variable()` creates mutable tensors used during model training.
- `tf.zeros()` creates tensors filled with zeros.
- `tf.ones()` creates tensors filled with ones.
- `tf.random.normal()` generates tensors with random values following a normal distribution.

These tensor creation methods are commonly used when building and training neural networks in TensorFlow.

In [2]:
import tensorflow as tf

scalar_tensor = tf.constant(5)
vector_tensor = tf.constant([1, 2, 3, 4])

matrix_tensor = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
zeros_tensor = tf.zeros([3, 3])
ones_tensor = tf.ones([2, 2])

# Printing Tensors
print("Scalar Tensor:")
print(scalar_tensor)

print("\nVector Tensor:")
print(vector_tensor)

print("\nMatrix Tensor:")
print(matrix_tensor)

print("\n3D Tensor:")
print(tensor_3d)

print("\nZeros Tensor:")
print(zeros_tensor)

print("\nOnes Tensor:")
print(ones_tensor)

Scalar Tensor:
tf.Tensor(5, shape=(), dtype=int32)

Vector Tensor:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Matrix Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

3D Tensor:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)

Zeros Tensor:
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

Ones Tensor:
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


## 2. Tensor Operations in TensorFlow

TensorFlow provides various operations to manipulate tensors efficiently. Some common operations include tensor addition, matrix multiplication, reshaping, and transposition.

### Operations Performed

1. **tf.ones_like()** – Creates a tensor of ones with the same shape as another tensor.
2. **tf.add()** – Performs element-wise addition between tensors.
3. **tf.matmul()** – Performs matrix multiplication.
4. **tf.reshape()** – Changes the shape of a tensor without changing its data.
5. **tf.transpose()** – Swaps the dimensions of a tensor (rows become columns and vice versa).

### Example


In [3]:
import tensorflow as tf

matrix_tensor = tf.constant([[1, 2], [3, 4]])

ones_tensor = tf.ones_like(matrix_tensor)
tensor_add = tf.add(matrix_tensor, ones_tensor)
matrix_mult = tf.matmul(matrix_tensor, matrix_tensor)
reshaped_tensor = tf.reshape(matrix_tensor, [4, 1])
transpose_tensor = tf.transpose(matrix_tensor)

print("Original Matrix:")
print(matrix_tensor)

print("\nTensor of Ones:")
print(ones_tensor)

print("\nAddition Result:")
print(tensor_add)

print("\nMatrix Multiplication Result:")
print(matrix_mult)

print("\nReshaped Tensor:")
print(reshaped_tensor)

print("\nTranspose of Matrix:")
print(transpose_tensor)

Original Matrix:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Tensor of Ones:
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)

Addition Result:
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)

Matrix Multiplication Result:
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)

Reshaped Tensor:
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)

Transpose of Matrix:
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


## 3. Accessing Elements in a Tensor

TensorFlow allows you to access specific elements within a tensor using indexing and slicing operations. These operations work similarly to Python lists and NumPy arrays, making it easy to retrieve individual values or subsets of data from a tensor.

### Indexing

Indexing is used to access a single element from a tensor by specifying its position.

### Slicing

Slicing is used to extract a portion of a tensor by specifying a range of indices.

### Example

```python
import tensorflow as tf

# Create a vector tensor
vector_tensor = tf.constant([1, 2, 3, 4])

# Access the first element
first_element = vector_tensor[0]

# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2],
                             [3, 4]])

# Slice the matrix
matrix_slice = matrix_tensor[:2, :]
```

### Explanation

- `vector_tensor[0]` retrieves the first element of the vector tensor.
- `matrix_tensor[:2, :]` selects all rows up to index 2 (exclusive) and all columns.
- Tensor slicing follows the same syntax as NumPy arrays.

### Benefits of Indexing and Slicing

- Access specific values efficiently.
- Extract subsets of data for analysis.
- Prepare data for machine learning models.
- Manipulate tensors without altering the original data structure.

### Conclusion

Indexing and slicing are essential tensor operations that allow developers to access and manipulate specific portions of data efficiently within TensorFlow applications.

In [4]:
import tensorflow as tf

# Create a vector tensor
vector_tensor = tf.constant([1, 2, 3, 4])

# Access the first element
first_element = vector_tensor[0]

# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2],
                             [3, 4]])

# Slice the matrix
matrix_slice = matrix_tensor[:2, :]

print("Vector Tensor:")
print(vector_tensor)

print("\nFirst Element:")
print(first_element)

print("\nMatrix Tensor:")
print(matrix_tensor)

print("\nMatrix Slice:")
print(matrix_slice)

Vector Tensor:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

First Element:
tf.Tensor(1, shape=(), dtype=int32)

Matrix Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Matrix Slice:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## 4. Changing Tensor Shape

TensorFlow provides the `tf.reshape()` function to change the shape of a tensor without modifying its underlying data. Reshaping is commonly used when preparing data for machine learning and deep learning models, which often require inputs in specific dimensions.

### Why Reshape a Tensor?

- Prepare data for neural networks.
- Convert data into the required input format.
- Change tensor dimensions while preserving the original values.
- Simplify tensor manipulation and processing.

### Example

```python
import tensorflow as tf

# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2],
                             [3, 4]])

# Reshape the tensor
reshaped_tensor = tf.reshape(matrix_tensor, [4, 1])
```

### Explanation

The original tensor has a shape of `(2, 2)`:

```text
[[1, 2],
 [3, 4]]
```

After reshaping to `(4, 1)`:

```text
[[1],
 [2],
 [3],
 [4]]
```

The total number of elements remains the same (4 elements), but their arrangement changes.

### Key Point

When reshaping a tensor, the total number of elements must remain unchanged. Otherwise, TensorFlow will raise an error.

### Conclusion

The `tf.reshape()` function is a powerful tool for modifying tensor dimensions and preparing data for machine learning and deep learning applications.

In [6]:
import tensorflow as tf

# Create a matrix tensor
matrix_tensor = tf.constant([[1, 2],
                             [3, 4]])

# Reshape the tensor
reshaped_tensor = tf.reshape(matrix_tensor, [4, 1])

print("Original Tensor:")
print(matrix_tensor)

print("\nOriginal Shape:")
print(matrix_tensor.shape)

print("\nReshaped Tensor:")
print(reshaped_tensor)

print("\nNew Shape:")
print(reshaped_tensor.shape)

Original Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Original Shape:
(2, 2)

Reshaped Tensor:
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)

New Shape:
(4, 1)


# Tensors in Neural Networks

Tensors play a fundamental role in neural networks and are used to represent data, model parameters, and outputs throughout the learning process. In TensorFlow, every computation within a neural network is performed using tensors.

## Role of Tensors in Neural Networks

### 1. Input Data

Input data such as images, text, audio, or tabular datasets are represented as tensors.

For example, an image dataset is commonly represented as a 4D tensor with the following shape:

```python
[batch_size, height, width, channels]
```

Example:

```python
[32, 224, 224, 3]
```

Where:

- **32** = Number of images in a batch
- **224** = Image height
- **224** = Image width
- **3** = RGB color channels

---

### 2. Weights and Biases

The weights and biases of neural network layers are also represented as tensors. These parameters are adjusted during training to improve the model's performance.

Example:

```python
Weight Matrix Shape: [10, 64]
Bias Vector Shape: [64]
```

---

### 3. Layer Outputs

The output generated by each layer after applying operations such as matrix multiplication, activation functions, convolutions, or pooling is represented as a tensor.

These intermediate tensors are passed from one layer to the next until the final prediction is produced.

---

## How Tensors Flow Through a Neural Network in TensorFlow

Consider a simple neural network trained on tabular data.

### Input Tensor

The training data may have the following shape:

```python
X_train.shape = (100, 10)
```

This means:

- **100 samples**
- **10 features per sample**

The input data is represented as a tensor of shape:

```python
[100, 10]
```

---

### Hidden Layer Processing

The input tensor is multiplied by weight tensors and combined with bias tensors.

```text
Input Tensor → Hidden Layer → Activation Function
```

The resulting output is another tensor that serves as input to the next layer.

---

### Output Tensor

After processing through the network, the model generates predictions.

Example output shape:

```python
[100, 1]
```

This indicates that the model produces one prediction for each of the 100 samples.

---

## Training and Backpropagation

During training:

1. Input tensors are passed through the network.
2. Predictions are generated as output tensors.
3. The loss function computes the error.
4. Backpropagation calculates gradients.
5. Weight and bias tensors are updated using an optimizer.

This process repeats until the model learns the optimal parameters.

---

## Key Points

- Tensors are the primary data structures used in neural networks.
- Input data, weights, biases, and outputs are all represented as tensors.
- TensorFlow performs computations efficiently using tensor operations.
- During training, tensors are continuously updated through backpropagation.
- Understanding tensors is essential for building and training deep learning models.

## Conclusion

Tensors form the backbone of neural networks in TensorFlow. They represent data at every stage of the learning process, from input features to final predictions. By efficiently handling multi-dimensional data, tensors enable TensorFlow to build powerful machine learning and deep learning applications.

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

X_train = tf.random.normal([100, 10])
y_train = tf.random.normal([100, 1])

model = Sequential([
    Dense(64, activation='relu', input_shape=(10,)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

model.fit(X_train, y_train, epochs=10)

Epoch 1/10


C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 1.0521  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9441 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8780 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8209 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7895
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7566
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7334 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7156 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6969
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6812 
